# Generated by Django 4.2.30 on 2026-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audit_remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_url',
            field=models.URLField(blank=True, verbose_name='外部封面地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('wechat', '微信'), ('alipay', '支付宝'), ('bank', '银行卡'), ('free', '免费')], default='alipay', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退款时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_no',
            field=models.CharField(blank=True, max_length=120, verbose_name='第三方交易号'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='certificate_file',
            field=models.FileField(blank=True, upload_to='teacher_applications/certificates/%Y/%m/', verbose_name='资质证明上传'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='sample_video',
            field=models.FileField(blank=True, upload_to='teacher_applications/videos/%Y/%m/', verbose_name='试讲视频上传'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='外部头像地址'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='文件大小字节'),
        ),
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, upload_to='courses/video_posters/%Y/%m/', verbose_name='视频封面上传'),
        ),
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('upload', '本地上传'), ('external', '外部地址'), ('vod', '云点播')], default='upload', max_length=20, verbose_name='视频来源'),
        ),
        migrations.AddField(
            model_name='video',
            name='transcode_status',
            field=models.CharField(default='pending', max_length=30, verbose_name='转码状态'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to='courses/videos/%Y/%m/', verbose_name='视频文件上传'),
        ),
        migrations.AddField(
            model_name='video',
            name='vod_file_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='云点播文件ID'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('visible', '显示'), ('hidden', '隐藏'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, upload_to='courses/covers/%Y/%m/', verbose_name='封面图上传'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='头像上传'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='外部视频地址'),
        ),
    ]
