# Generated by Django 4.2.30 on 2026-07-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=150, verbose_name='附件名称')),
                ('file', models.FileField(upload_to='courses/attachments/%Y/%m/', verbose_name='附件上传')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('audio', '音频'), ('archive', '压缩包'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小字节')),
                ('sort_weight', models.IntegerField(default=0, verbose_name='排序权重')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程附件',
                'verbose_name_plural': '课程附件',
                'ordering': ['sort_weight', 'id'],
            },
        ),
    ]
